name: pertamina_app
description: Aplikasi monitoring kinerja pekerja pada IT Pertamina Lhokseumawe

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  intl: ^0.17.0

  firebase_core: ^2.32.0
  firebase_database: ^10.0.0
  cloud_firestore: ^4.17.5
  crypto: ^3.0.1
  firebase_storage: ^11.7.7
  firebase_auth: ^4.20.0
  image_picker: ^1.1.1
  file_picker: ^8.0.6
  path_provider: ^2.1.4
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  dio: ^5.5.0+1
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
  - assets/default_profile_picture.png
